stages:
  - deploy

deploy-testh:
  tags:
    - kub-prod
  stage: deploy
  image: alpine
  only:
    - stage
  before_script:
    - apk add --no-cache openssh rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_GITLAB" > ./ssh/id_rsa
    - chmod -R 600 ./ssh/
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - rsync -a --exclude="./ssh" --exclude=".gitlab-ci" . git@logistic:/var/www/logistic;
