stages:
  - deploy

deploy-testh:
  tags:
    - kub-prod
  stage: deploy
  image: alpine
  only:
    - stage
    - main
  before_script:
    - apk add --no-cache openssh rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_GITLAB" > ~/priv_key
    - chmod 600 ~/priv_key
    - if [ "$CI_COMMIT_BRANCH" == "stage" ]; then
        mv "$CONFIG_ENV_STAGE" ./.env;
        export DEPLOY_IP="172.17.233.7";
      fi
    - if [ "$CI_COMMIT_BRANCH" == "main" ]; then
        mv "$CONFIG_ENV_PROD" ./.env;
        export DEPLOY_IP="172.17.231.6";
      fi
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - rsync -avh --progress --chown=nginx:git --exclude=".git" --exclude=".gitlab-ci.yml" --exclude="storage" --exclude="node_modules" . git@$DEPLOY_IP:/var/www/logistic -e "ssh -o StrictHostKeyChecking=no -i ~/priv_key";
    - ssh -o StrictHostKeyChecking=no -i ~/priv_key git@$DEPLOY_IP 'cd /var/www/logistic && composer install --ignore-platform-reqs;'
