stages:
  - deploy

deploy-testh:
  tags:
    - kub-prod
  stage: deploy
  image: alpine
  only:
    - stage
  before_script:
    - apk add --no-cache openssh rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_GITLAB" > ~/priv_key
    - chmod 600 ~/priv_key
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - rsync -avh --exclude=".git" --exclude=".gitlab-ci.yml" --exclude="storage" --exclude=".env" --exclude="node_modules". git@172.31.11.149:/var/www/logistic  -e "ssh -o StrictHostKeyChecking=no -i ~/priv_key";
    - ssh -o StrictHostKeyChecking=no -i ~/priv_key git@172.31.11.149 'cd /var/www/logistic && composer install --ignore-platform-reqs;'
    - echo "'Value of CONFIG_ENV_STAGE:' $(cat ${CONFIG_ENV_STAGE})"
    - cat ${CONFIG_ENV_STAGE} >> .env || echo "Failed to write to .env"
    - echo "Contents of .env:"
    - cat .env

