<?php

namespace App\Infrastructure\Imports;

use Maatwebsite\Excel\Concerns\OnEachRow;
use Maatwebsite\Excel\Concerns\WithCalculatedFormulas;
use Maatwebsite\Excel\Concerns\WithColumnFormatting;
use Maatwebsite\Excel\Concerns\WithCustomValueBinder;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithValidation;
use Maatwebsite\Excel\DefaultValueBinder;
use Maatwebsite\Excel\Row;
use PhpOffice\PhpSpreadsheet\Cell\Cell;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\Shared\Date;

class ApplicationImportXlsx extends DefaultValueBinder implements ImportEntity,
    WithCustomValueBinder, WithCalculatedFormulas
//    , WithValidation
{
    public function bindValue(Cell $cell, $value): bool
    {
        $timeColumns = ['O', 'P'];

        // форматируем дату в нормальный вид
        if ($cell->getParent()->getCurrentColumn() === 'N' && $value) {
            $value = Date::excelToDateTimeObject($value)->format('Y-m-d');
        }

        if (in_array($cell->getParent()->getCurrentColumn(), $timeColumns)) {
            $value = Date::excelToDateTimeObject($value)->format('H:i');
        }

        if ($cell->getParent()->getCurrentColumn() === 'U' && $value) {
            $value = floatval($value);
        }
//        if ($cell->getParent()->getCurrentColumn() === 'AC') {
//            $cell->setValueExplicit($value, DataType::TYPE_STRING);
//        }
        return parent::bindValue($cell, $value); // TODO: Change the autogenerated stub
    }
//
//    public function rules(): array
//    {
//        // TODO: Implement rules() method.
//    }
}