<?php

namespace App\Infrastructure\Imports;

use Maatwebsite\Excel\Concerns\WithCalculatedFormulas;
use Maatwebsite\Excel\Concerns\WithCustomValueBinder;
use Maatwebsite\Excel\DefaultValueBinder;
use PhpOffice\PhpSpreadsheet\Cell\Cell;
use PhpOffice\PhpSpreadsheet\Shared\Date;

class ApplicationImportXlsx extends DefaultValueBinder implements ImportEntity,
    WithCustomValueBinder, WithCalculatedFormulas
{
    public function bindValue(Cell $cell, $value): bool
    {
        $timeColumns = ['O', 'P'];

        // форматируем дату в нормальный вид
        if ($cell->getParent()->getCurrentColumn() === 'N' && $value) {
            $value = Date::excelToDateTimeObject($value)->format('d.m.Y');
        }

        if (in_array($cell->getParent()->getCurrentColumn(), $timeColumns)) {
            $value = Date::excelToDateTimeObject($value)->format('H:i');
        }

        // форматируем цену в float
        if ($cell->getParent()->getCurrentColumn() === 'U' && $value) {
            $value = floatval($value);
        }

        return parent::bindValue($cell, $value); // TODO: Change the autogenerated stub
    }
}